#### Probabilities
For predicting the next character or word.

In [31]:
import torch

# Define probabilities
probabilities = torch.tensor([0.3, 0.7])
n_samples = 10

# Generate samples
samples = torch.multinomial(probabilities, n_samples, replacement=True)
print(samples)

tensor([0, 1, 1, 0, 1, 0, 0, 1, 0, 1])


In [32]:
# Concatenate tensors 
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [33]:
# Triangle lower matrix
# Important for predicting the next character or word (Future and history)

out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [34]:
# Triangle upper matrix
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [35]:
# Masking /converts the lower triangle to -inf
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [36]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [37]:
input = torch.zeros(2,3,4)
print(input.shape)
out = input.transpose(0,2)
print(out.shape)


torch.Size([2, 3, 4])
torch.Size([4, 3, 2])


In [38]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack((tensor1, tensor2, tensor3))
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])