In [3]:
import torch

In [5]:
# 6 random integers from -100 to 100 inside of an tensor
randint = torch.randint(-100, 100, (6,))
print(randint)

tensor([ 66, -56, -77, -85,  72,  43])


In [7]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [9]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(2, 3)
ones